version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=DEBUG
      - FEATURE_FLAGS=local_development,debug
    volumes:
      - ./src:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  app_staging:
    build: .
    ports:
      - "8001:8000"
    environment:
      - LOG_LEVEL=INFO
      - FEATURE_FLAGS=metrics,api_logging
    volumes:
      - ./src:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  app_prod:
    build: .
    ports:
      - "8002:8000"
    environment:
      - LOG_LEVEL=WARNING
      - FEATURE_FLAGS=
    volumes:
      - ./src:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
